import {
  AlarmClock,
  Anchor,
  Apple,
  Archive,
  Armchair,
  Axe,
  Backpack,
  Banana,
  Battery,
  Bed,
  Beer,
  Bell,
  Bike,
  Book,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Brush,
  Building,
  Building2,
  Bus,
  Cake,
  Calculator,
  Camera,
  Car,
  Carrot,
  Cat,
  Cherry,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Cookie,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dog,
  Droplet,
  Drum,
  Dumbbell,
  Egg,
  Factory,
  Fan,
  FileText,
  Fish,
  Flame,
  Flower2,
  Folder,
  FolderOpen,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  Home,
  IceCream,
  Key,
  Lamp,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Map,
  MapPin,
  Medal,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Package,
  Paintbrush,
  Palette,
  Pen,
  Pencil,
  Phone,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Printer,
  Puzzle,
  Radio,
  Refrigerator,
  Rocket,
  Ruler,
  Sandwich,
  Scissors,
  Server,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Smartphone,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tag,
  Tent,
  Thermometer,
  Timer,
  Train,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  Warehouse,
  Watch,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ENTITY_ICONS = {
  "map-pin": MapPin,
  map: Map,
  home: Home,
  building: Building,
  "building-2": Building2,
  warehouse: Warehouse,
  store: Store,
  factory: Factory,
  tent: Tent,
  mountain: Mountain,
  archive: Archive,
  folder: Folder,
  "folder-open": FolderOpen,
  box: Box,
  boxes: Boxes,
  package: Package,
  layers: Layers,
  backpack: Backpack,
  briefcase: Briefcase,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  key: Key,
  lock: Lock,
  tag: Tag,
  shield: Shield,
  wrench: Wrench,
  hammer: Hammer,
  axe: Axe,
  shovel: Shovel,
  scissors: Scissors,
  ruler: Ruler,
  pen: Pen,
  pencil: Pencil,
  brush: Brush,
  paintbrush: Paintbrush,
  palette: Palette,
  book: Book,
  "book-open": BookOpen,
  "file-text": FileText,
  clipboard: Clipboard,
  calculator: Calculator,
  camera: Camera,
  phone: Phone,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  tv: Tv,
  printer: Printer,
  server: Server,
  database: Database,
  "hard-drive": HardDrive,
  cpu: Cpu,
  headphones: Headphones,
  watch: Watch,
  glasses: Glasses,
  mic: Mic,
  radio: Radio,
  music: Music,
  guitar: Guitar,
  piano: Piano,
  drum: Drum,
  shirt: Shirt,
  umbrella: Umbrella,
  lightbulb: Lightbulb,
  lamp: Lamp,
  fan: Fan,
  plug: Plug,
  battery: Battery,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  flame: Flame,
  droplet: Droplet,
  waves: Waves,
  leaf: Leaf,
  "tree-pine": TreePine,
  flower: Flower2,
  apple: Apple,
  banana: Banana,
  cherry: Cherry,
  carrot: Carrot,
  egg: Egg,
  coffee: Coffee,
  utensils: Utensils,
  pizza: Pizza,
  sandwich: Sandwich,
  cookie: Cookie,
  cake: Cake,
  "ice-cream": IceCream,
  beer: Beer,
  car: Car,
  bus: Bus,
  truck: Truck,
  train: Train,
  plane: Plane,
  ship: Ship,
  anchor: Anchor,
  compass: Compass,
  globe: Globe,
  bike: Bike,
  trophy: Trophy,
  medal: Medal,
  crown: Crown,
  gem: Gem,
  gift: Gift,
  heart: Heart,
  star: Star,
  sparkles: Sparkles,
  puzzle: Puzzle,
  gamepad: Gamepad2,
  rocket: Rocket,
  cat: Cat,
  dog: Dog,
  fish: Fish,
  bed: Bed,
  sofa: Sofa,
  armchair: Armchair,
  refrigerator: Refrigerator,
  pill: Pill,
  syringe: Syringe,
  stethoscope: Stethoscope,
  thermometer: Thermometer,
  dumbbell: Dumbbell,
  alarm: AlarmClock,
  clock: Clock,
  timer: Timer,
  bell: Bell,
  "graduation-cap": GraduationCap,
  "credit-card": CreditCard,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ENTITY_ICONS;

export const ICON_NAMES = Object.keys(ENTITY_ICONS) as IconName[];

export const DEFAULT_LOCATION_ICON: IconName = "map-pin";
export const DEFAULT_ITEM_ICON: IconName = "package";

export function isValidIconName(name: string): name is IconName {
  return name in ENTITY_ICONS;
}

export function parseIconName(
  name: string | null | undefined,
  fallback: IconName
): IconName {
  if (name && isValidIconName(name)) return name;
  return fallback;
}

export function getEntityIcon(name: string | null | undefined, fallback: IconName): LucideIcon {
  return ENTITY_ICONS[parseIconName(name, fallback)];
}
